# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: <your_glogin> <your_email>                 +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/14 by <username>            #+#    #+#              #
#    Updated: 2023/08/14 by <username>           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror
AR = ar rcs
RM = rm -f

# Mandatory source files
M_SRCS = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
         ft_strlen.c ft_memset.c 


# Bonus source files
B_SRCS = 

# Object files
M_OBJS = $(M_SRCS:.c=.o)
B_OBJS = $(B_SRCS:.c=.o)

# Header file
HEADER = libft.h

# Colors
GREEN = \033[0;32m
RED = \033[0;31m
RESET = \033[0m

all: $(NAME)

$(NAME): $(M_OBJS)
	@$(AR) $(NAME) $(M_OBJS)
	@echo "$(GREEN)✅ $(NAME) created$(RESET)"

%.o: %.c $(HEADER)
	@$(CC) $(CFLAGS) -c $< -o $@

bonus: $(M_OBJS) $(B_OBJS)
	@$(AR) $(NAME) $(M_OBJS) $(B_OBJS)
	@echo "$(GREEN)✅ Bonus added to $(NAME)$(RESET)"

clean:
	@$(RM) $(M_OBJS) $(B_OBJS)
	@echo "$(RED)🧹 Object files removed$(RESET)"

fclean: clean
	@$(RM) $(NAME)
	@echo "$(RED)🧹 $(NAME) removed$(RESET)"

re: fclean all

.PHONY: all bonus clean fclean re